### ISSUE TITLE
S4A overwrites external changes

### ISSUE THREAD

**Issue by randomeizer** [swiftforarduino/community#8]
I have been using an external editor to work on my project, partly because of familiarity/muscle-memory, partly performance of S4A with larger files. I'm still building in S4A of course, and currently I have to quit/reload the app whenever I do a build because whenever I run a build, S4A overwrites any changes I make externally while S4A is running. In other words, whatever version it cached on load gets written back to the file.

It would be nice if it would do the reverse - load any external changes on Build.

**Comment by carlos4242** [comment]
Fixed in 4.3. There is now a setting to prevent this happening. Look in preferences, advanced.
