### ISSUE TITLE
AVR Swift library usage in Xcode

### ISSUE THREAD

**Issue by OmerFlame** [swiftforarduino/community#9]
Hello, I recently purchased a copy of Swift For Arduino and when I opened the IDE, I immediately noticed that there is no autocomplete support. Is there any way to use Xcode with the AVR library and create a custom build system that utilizes your own build process?

**Comment by carlos4242** [comment]
The short answer is yes and no!!

So, editing files in xcode. Yes. A few of our community do this and I think it is straightforward. I will add you to our slack channels so you can ask them how they do it if it’s not clear. Mark Swanson and David Peterson are both doing this regularly. Both prefer xcode as an editor and just use the Swift for Arduino IDE to build and upload onto the device (the Arduino Uno). That works well for them.

For autocomplete, I don’t think that will help you as much as you’d like. The AVR library is written for and compiled on a completely different architecture than the ones xcode is used to (the AVR architecture) and I don’t think xcode will “see” the AVR module. Xcode cannot compile or autocomplete AVR definitions.


Autocomplete must be the number one feature I am asked for these days. It’s for sure on the roadmap in the near future. For now your best approaches are look at the Documentation window in our IDE, check out the snippets panel on the left (these are extremely helpful) and finally check out the examples in Getting Started in the code folder on your dmg file.

Carl

**Comment by carlos4242** [comment]
Closing this issue as we do not plan to do this in the near future. Some people use Xcode as the editor of the files on disk and build using the S4A menu in the top right hand corner of the screen. Also, as an alternative to autocomplete, consider using code snippets. These often give you the right code when you need it. As a final feature, you can turn on insights in modern builds of the IDE and that will filter your code snippets and help according to what you are typing in the IDE, which acts somewhat like autocomplete.
